name: Deploy Images to GHCR

permissions:
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and Push Docker Image'
        run: |
          docker build . \
            --tag ghcr.io/${{ github.repository_owner }}/marvel-app:latest \
            --build-arg NEXT_PUBLIC_TEST=NEXT_PUBLIC_TEST_VAR \
            --build-arg NEXT_PUBLIC_MARVEL_API_URL=${{ secrets.API_URL }} \
            --build-arg NEXT_PUBLIC_MARVEL_PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
            --build-arg NEXT_PUBLIC_MARVEL_PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}
          docker push ghcr.io/${{ github.repository_owner }}/marvel-app:latest