name: Deploy Images to GHCR

permissions:
  packages: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: 'Build and Push Docker Image'
      #   run: |
      #     docker build . \
      #       --tag ghcr.io/${{ github.repository_owner }}/marvel-app:latest
      #     docker push ghcr.io/${{ github.repository_owner }}/marvel-app:latest

      - name: Debug SSH Key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEPLOY_HOST }} "whoami"

      - name: 'Start SSH Agent and Add Key'
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEPLOY_KEY }}" | ssh-add -
      
      # - name: 'Deploy via SSH'
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "bash ${{ secrets.DEPLOY_FOLDER }}/${{ secrets.DEPLOY_SCRIPT_SH }}"